<?php
/**
* Copyright © 2019 Roma Technology Limited. All rights reserved.
* See COPYING.txt for license details.
*/
$information = $block->getInformation();
?>
<?php if ($information): ?>
    <?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
    <ul class="form-list checkout-agreements" id="payment_form_<?= /* @noEscape */ $methodCode ?>" style="display:none;">
        <li>
            <div class="<?= /* @noEscape */ $methodCode ?>-information-content checkout-agreement-item-content">
                <?= /* @noEscape */ nl2br($block->escapeHtml($information)) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>